using System;
using System.IO;
using System.Text;

namespace Lemur
{
    public class LeHecmwControl
    {
        private string _meshFile;
        private string _controlFile;
        private string _resultName;

        public LeHecmwControl()
        {
            string name = "lemur";
            SetValues(name + ".msh", name + ".cnt", name);
        }

        public LeHecmwControl(string name)
        {
            SetValues(name + ".msh", name + ".cnt", name);
        }

        public LeHecmwControl(string meshFile, string controlFile)
        {
            SetValues(meshFile, controlFile, "lemur");
        }

        public LeHecmwControl(string meshFile, string controlFile, string resultName)
        {
            SetValues(meshFile, controlFile, resultName);
        }

        private void SetValues(string meshFile, string controlFile, string resultName)
        {
            _meshFile = meshFile;
            _controlFile = controlFile;
            _resultName = resultName;
        }

        public string ToDat()
        {
            var sb = new StringBuilder();
            sb.AppendLine($"#");
            sb.AppendLine($"# Global Control Data File generated by Lemur");
            sb.AppendLine($"# at {DateTime.Now}");
            sb.AppendLine($"#");
            sb.AppendLine($"#");
            sb.AppendLine($"# for solver");
            sb.AppendLine($"#");
            sb.AppendLine($"!MESH, NAME=fstrMSH,TYPE=HECMW-ENTIRE");
            sb.AppendLine($"{_meshFile}");
            sb.AppendLine($"#");
            sb.AppendLine($"# for visualizer");
            sb.AppendLine($"#");
            sb.AppendLine($"!MESH, NAME=mesh,TYPE=HECMW-ENTIRE");
            sb.AppendLine($"{_meshFile}");
            sb.AppendLine($"#");
            sb.AppendLine($"# for solver");
            sb.AppendLine($"#");
            sb.AppendLine($"!CONTROL,NAME=fstrCNT");
            sb.AppendLine($"{_controlFile}");
            sb.AppendLine($"!RESTART,NAME=restart_out,IO=OUT");
            sb.AppendLine($"{_resultName}.restart");
            sb.AppendLine($"!RESULT,NAME=fstrRES,IO=OUT");
            sb.AppendLine($"{_resultName}.res");
            sb.AppendLine($"#");
            sb.AppendLine($"# for visualizer");
            sb.AppendLine($"#");
            sb.AppendLine($"!RESULT,NAME=result,IO=IN");
            sb.AppendLine($"{_resultName}.res");
            sb.AppendLine($"!RESULT,NAME=vis_out,IO=OUT");
            sb.AppendLine($"{_resultName}.vis");

            return sb.ToString();
        }

        public void Serialize(string dir)
        {
            string path = Path.Combine(dir, "hecmw_ctrl.dat");
            File.WriteAllText(path, ToDat());
        }
    }
}
